#if UNITY_EDITOR
using System;
using System.Collections;
using System.Linq;
using System.Reflection;
using UnityEngine;
namespace HollowDemo {
 public sealed class ActivationSmokeProbe:MonoBehaviour {
 static void Check(bool ok,string msg){if(!ok)throw new Exception("ACTIVATION FAILED: "+msg);Debug.Log("DEMO_ACTIVATION_CHECK: "+msg);}
 IEnumerator Start(){yield return null;SaveStore.testPath=System.IO.Path.GetFullPath("Temp/Activation/progress.json");var game=DemoGame.Instance;while(game.Activation==null)yield return null;var activation=game.Activation;int enemyCount=game.Enemies.Length,checkpointCount=game.Checkpoints.Length;var enemies=game.Enemies.ToArray();var homes=enemies.Select(e=>e.Home).ToArray();int all=FindObjectsOfType<Collider2D>().Length;Check(activation.ChunkCount>1,"runtime chunks created");game.NewGame();yield return new WaitForSecondsRealtime(.6f);Check(game.HasRun&&!game.Player.Dead,"spawn remains safe after culling");game.SetScreen(GameScreen.Pause);int near=FindObjectsOfType<Collider2D>().Length;Check(activation.ActiveChunkCount<activation.ChunkCount&&near<all,"remote colliders inactive: "+all+" -> "+near+", chunks "+activation.ActiveChunkCount+" / "+activation.ChunkCount);Check(enemies.Select((e,i)=>Vector2.Distance(e.Home,homes[i])<.001f).All(x=>x),"chunk reparenting preserves enemy homes");
 var origin=(Vector2)game.Player.transform.position;var far=enemies.Where(e=>e.kind!=EnemyKind.Shield).OrderByDescending(e=>Vector2.Distance(origin,e.Home)).First();activation.ActivateAt(far.Home);Check(far.gameObject.activeInHierarchy,"remote area activates on movement");int health=far.Health;far.TakeHit(1,far.transform.position,1);health=far.Health;activation.ActivateAt(origin);Check(!far.gameObject.activeInHierarchy,"remote enemy suspended");activation.ActivateAt(far.Home);Check(far.Health==health,"region reentry preserves damaged health");far.TakeHit(999,far.transform.position,1);activation.ActivateAt(origin);activation.ActivateAt(far.Home);Check(!far.gameObject.activeSelf,"dead enemy stays dead across region activation");
 var pickup=FindObjectsOfType<Pickup>(true).First(p=>p.transform.parent.name.StartsWith("运行区域"));activation.ActivateAt(pickup.transform.position);pickup.Interact(game);activation.ActivateAt(origin);activation.ActivateAt(pickup.transform.position);Check(!pickup.gameObject.activeSelf&&game.PickupCollected(pickup.persistentId),"collected pickup remains collected");
 var checkpoint=game.Checkpoints.OrderByDescending(c=>Vector2.Distance(origin,c.spawnPoint.position)).First(c=>{activation.ActivateAt(c.spawnPoint.position);return game.World.TryGetSpawn(c.spawnPoint,out _);});activation.ActivateAt(checkpoint.spawnPoint.position);game.ActivateCheckpoint(checkpoint);activation.ActivateAt(origin);game.ContinueGame();yield return new WaitForSecondsRealtime(.6f);game.SetScreen(GameScreen.Pause);Check(game.Enemies.Length==enemyCount&&game.Checkpoints.Length==checkpointCount,"continue caches include inactive regions");Check(Vector2.Distance(game.Player.transform.position,checkpoint.spawnPoint.position)<2&&!game.Player.Dead,"continue activates remote checkpoint terrain before spawn");Check(!far.gameObject.activeSelf&&game.PickupCollected(pickup.persistentId),"save retains death and pickup");
 game.SetScreen(GameScreen.None);game.Player.GetComponent<Rigidbody2D>().constraints=RigidbodyConstraints2D.FreezeAll;game.Player.KillInstantly();yield return new WaitForSecondsRealtime(1.3f);Check(!game.Player.Dead&&Vector2.Distance(game.Player.transform.position,checkpoint.spawnPoint.position)<2,"death activates checkpoint region before respawn");game.SetScreen(GameScreen.Pause);Check(!pickup.gameObject.activeSelf,"death does not restore collected item");
 var timed=game.Enemies.Where(e=>e.Health>0).OrderByDescending(e=>Vector2.Distance(game.Player.transform.position,e.Home)).First();activation.ActivateAt(timed.Home);var timer=typeof(EnemyBrain).GetField("nextPhase",BindingFlags.NonPublic|BindingFlags.Instance);timer.SetValue(timed,Time.time+5);activation.ActivateAt(game.Player.transform.position);Check(!timed.gameObject.activeInHierarchy,"timer test enemy suspended");Time.timeScale=1;yield return new WaitForSecondsRealtime(.25f);activation.ActivateAt(timed.Home);Check(Mathf.Abs((float)timer.GetValue(timed)-Time.time-5)<.06f,"inactive region preserves attack warning timer");Time.timeScale=0;
 activation.RestoreAll();Check(activation.ActiveChunkCount==activation.ChunkCount,"all chunks can be restored for initialization");activation.ActivateAt(game.Player.transform.position);Debug.Log("DEMO_SMOKE_OK: region activation state and remote checkpoint");}
 }
}
#endif
