#if UNITY_EDITOR
using System;
using System.Collections;
using System.Reflection;
using UnityEngine;
namespace HollowDemo {
 public sealed class GrappleJumpSmokeProbe:MonoBehaviour {
 static void Check(bool ok,string msg){if(!ok)throw new Exception("GRAPPLE JUMP FAILED: "+msg);Debug.Log("DEMO_GRAPPLE_CHECK: "+msg);}
 static void Jump(PlayerMotor p){p.ReleaseGrapple();typeof(PlayerMotor).GetField("jumpUntil",BindingFlags.Instance|BindingFlags.NonPublic).SetValue(p,Time.time+p.jumpBufferWindow);}
 IEnumerator Start(){yield return null;SaveStore.testPath=System.IO.Path.GetFullPath("Temp/GrappleJump/progress.json");var g=DemoGame.Instance;g.NewGame();yield return new WaitForSecondsRealtime(.6f);g.Checkpoints[0].Interact(g);yield return null;Canvas.ForceUpdateCanvases();var allocation=FindObjectOfType<FlaskAllocationCanvas>();foreach(var text in allocation.GetComponentsInChildren<UnityEngine.UI.Text>())Check(text.font!=null&&text.cachedTextGenerator.vertexCount>0,"allocation text has runtime Chinese font and mesh: "+text.name);g.SetScreen(GameScreen.None);var p=g.Player;var body=p.GetComponent<Rigidbody2D>();var floor=new GameObject("Test floor",typeof(BoxCollider2D),typeof(GroundSurface));floor.layer=8;floor.transform.position=new Vector3(1000,1000);floor.transform.localScale=new Vector3(15,1,1);floor.GetComponent<BoxCollider2D>().size=Vector2.one;p.Respawn(new Vector2(1000,1001.2f));Physics2D.SyncTransforms();yield return new WaitForFixedUpdate();yield return new WaitForFixedUpdate();Check(p.Grounded,"ground start");var hook=new GameObject("Test hook",typeof(GrapplePoint));hook.transform.position=p.transform.position+Vector3.up*7;var platform=Instantiate(UnityEditor.AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Prefabs/World/DropPlatform.prefab"),p.transform.position+Vector3.up*2,Quaternion.identity);Physics2D.SyncTransforms();Check(p.TryGrapple(),"grapple detects hook through one-way platform");yield return new WaitForSeconds(.28f);Check(!p.Grounded&&p.Grappling,"grapple lifts player beyond coyote window");Check(p.transform.position.y>platform.GetComponent<Collider2D>().bounds.max.y,"upward grapple passes through platform");Destroy(platform);Jump(p);yield return new WaitForFixedUpdate();Check(body.velocity.y>8&&p.CanDoubleJump,"first jump preserves double jump");Jump(p);yield return new WaitForFixedUpdate();Check(body.velocity.y>8&&!p.CanDoubleJump,"second jump consumes double jump");hook.transform.position=p.transform.position+Vector3.up*6;Check(p.TryGrapple(),"air regrapple");yield return new WaitForSeconds(.15f);body.velocity=Vector2.zero;Jump(p);yield return new WaitForFixedUpdate();Check(!p.CanDoubleJump&&body.velocity.y<p.secondJumpSpeed-1,"air regrapple does not refill jumps");p.Respawn(new Vector2(1000,1001.2f));Physics2D.SyncTransforms();yield return new WaitForFixedUpdate();yield return new WaitForFixedUpdate();Check(p.CanDoubleJump,"landing restores jump");hook.transform.position=p.transform.position+Vector3.up*6;p.enableDoubleJump=false;Check(p.TryGrapple(),"grapple with double jump disabled");yield return new WaitForSeconds(.25f);Jump(p);yield return new WaitForFixedUpdate();Check(body.velocity.y>8&&!p.CanDoubleJump,"single retained ground jump respects ability toggle");Debug.Log("DEMO_SMOKE_OK: grapple ground jump and double jump");}
 }
}
#endif
