#if UNITY_EDITOR
using System;
using System.Collections;
using System.Linq;
using UnityEngine;
using UnityEditor;
namespace HollowDemo {
public sealed class SkillSmokeProbe:MonoBehaviour {
static void Check(bool ok,string msg){if(!ok)throw new Exception("SKILL FAILED: "+msg);Debug.Log("DEMO_SKILL_CHECK: "+msg);}
IEnumerator Start(){yield return null;SaveStore.testPath=System.IO.Path.GetFullPath("Temp/SkillSmoke/progress.json");var g=DemoGame.Instance;while(g.Activation==null)yield return null;g.NewGame();yield return new WaitForSecondsRealtime(.6f);var p=g.Player;g.Checkpoints[0].Interact(g);Check(g.Screen==GameScreen.Checkpoint&&g.FlaskCapacity==3&&g.ManaFlaskCapacity==0,"checkpoint opens editable allocation");g.ChangeFlaskAllocation(1);Check(g.BloodFlaskCapacity==2&&g.FlaskCharges==2&&g.ManaFlaskCapacity==1&&g.ManaFlaskCharges==1,"shared container allocation and refill");g.SaveProgress();g.ContinueGame();yield return new WaitForSecondsRealtime(.6f);Check(g.BloodFlaskCapacity==2&&g.ManaFlaskCharges==1,"allocation and charges persist");g.SetScreen(GameScreen.None);
var body=p.GetComponent<Rigidbody2D>();body.constraints=RigidbodyConstraints2D.FreezeAll;Check(p.Mana==p.maxMana,"initial mana restored");int before=p.Mana;var configured=p.skillPrefab;p.skillPrefab=null;Check(!p.TryCast(Vector2.up)&&p.Mana==before,"missing prefab does not throw or spend mana");p.skillPrefab=configured;Check(configured!=null,"scene skill prefab assigned");Check(p.TryCast(Vector2.up)&&p.Mana==before-p.skillManaCost,"upward cast spends mana");var orb=FindObjectOfType<SkillOrb>();Check(orb.GetComponent<SpriteRenderer>().sprite.name=="ElectricOrb","electric orb sprite assigned");Check(orb.velocity.y>0&&Mathf.Abs(orb.velocity.x)<.01f,"orb uses upward direction");Destroy(orb.gameObject);Check(g.UseManaFlask()&&p.Mana==p.maxMana&&g.ManaFlaskCharges==0,"mana flask reusable recovery");Check(!g.UseManaFlask(),"empty mana flask does not restore");
yield return new WaitForSeconds(.35f);p.skillManaCost=p.maxMana+1;Check(!p.TryCast(Vector2.right),"insufficient mana prevents cast");p.skillManaCost=20;
p.transform.position=new Vector3(-1000,1000);body.position=p.transform.position;var enemy=Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Prefabs/Enemies/Patrol.prefab"),p.transform.position+Vector3.right*2,Quaternion.identity).GetComponent<EnemyBrain>();enemy.GetComponent<Rigidbody2D>().constraints=RigidbodyConstraints2D.FreezeAll;Physics2D.SyncTransforms();int enemyHp=enemy.Health;Check(p.TryCast(Vector2.right),"rightward cast");yield return new WaitForSeconds(.25f);Check(enemy.Health==enemyHp-p.skillDamage,"white orb damages enemy once");enemy.gameObject.SetActive(false);
if(SessionState.GetBool("HollowDemo.OrbSmoke",false)){Debug.Log("DEMO_SMOKE_OK: electric orb reference, sprite, mana and damage");yield break;}
if(!SessionState.GetBool("HollowDemo.DropSmoke",false)){
yield return new WaitForSeconds(1.1f);int hp=p.Health;p.ApplyEnvironmentalDamage(1);Check(p.Health==hp-1,"water damage removes health");p.Damage(1,p.transform.position);p.ApplyEnvironmentalDamage(1);Check(p.Health==hp-1,"water grants ordinary invulnerability");yield return new WaitForSeconds(1.1f);p.Damage(1,p.transform.position);hp=p.Health;p.ApplyEnvironmentalDamage(1);Check(p.Health==hp,"water respects ordinary invulnerability");
var ui=FindObjectOfType<PlayerHudCanvas>();g.TryCollectItem(Resources.Load<ItemDefinition>("Items/crystal"),17);yield return null;Check(ui.crystalCount.text==g.Crystals.ToString()&&ui.crystalCount.color.a>0&&ui.manaFill.fillAmount<1,"crystal number and mana Canvas update");
}
p.transform.position+=Vector3.up*10;body.position=p.transform.position;var platform=Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Prefabs/World/DropPlatform.prefab"),p.transform.position+Vector3.down*.82f,Quaternion.identity);Physics2D.SyncTransforms();platform.transform.position+=Vector3.up*(p.GetComponent<Collider2D>().bounds.min.y-platform.GetComponent<Collider2D>().bounds.max.y-.02f);Physics2D.SyncTransforms();Check(p.TryDropThrough(),"S Space drop ignores only one-way platform");Check(Physics2D.GetIgnoreCollision(platform.GetComponent<Collider2D>(),p.GetComponent<Collider2D>()),"temporary pair collision ignore");p.GetComponent<Rigidbody2D>().constraints=RigidbodyConstraints2D.FreezeRotation;
if(SessionState.GetBool("HollowDemo.DropSmoke",false)){yield return new WaitForSeconds(.8f);Check(p.GetComponent<Collider2D>().bounds.max.y<platform.GetComponent<Collider2D>().bounds.min.y,"player physically falls below platform");Check(!Physics2D.GetIgnoreCollision(platform.GetComponent<Collider2D>(),p.GetComponent<Collider2D>()),"collision restored after fully crossing");Destroy(platform);Debug.Log("DEMO_SMOKE_OK: drop platform detection, fall and collision restore");yield break;}Destroy(platform);
var kill=Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Prefabs/World/InstantDeathZone.prefab"),p.transform.position,Quaternion.identity);kill.transform.localScale=Vector3.one*5;Physics2D.SyncTransforms();yield return new WaitForFixedUpdate();yield return new WaitForFixedUpdate();Check(p.Dead,"contact instant death bypasses invulnerability");Destroy(kill);yield return new WaitForSecondsRealtime(1.3f);Check(!p.Dead&&p.Mana==p.maxMana&&g.FlaskCharges==2&&g.ManaFlaskCharges==1,"death refills assigned charges and mana");Debug.Log("DEMO_SMOKE_OK: skill hazards mana and allocation");}
}}
#endif
